{{ if .Values.podDisruptionBudget.enabled }}
apiVersion: {{ ternary "policy/v1" "policy/v1beta1" (semverCompare ">=1.21.0-0" .Capabilities.KubeVersion.Version ) }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "regatta.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "regatta.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "regatta.selectorLabels" . | nindent 6 }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
{{ end }}
