{{ if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "regatta.name" . }}
  labels:
    {{- include "regatta.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "regatta.selectorLabels" . | nindent 6 }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
{{ end }}
