{{- if .Values.maintenance.enabled }}
{{- if eq .Values.maintenance.secretKind "plaintext" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "regatta.name" . }}-maintenance-token
  labels:
    {{- include "regatta.labels" . | nindent 4 }}
data:
  token: {{ .Values.maintenance.token | b64enc }}
{{- end }}
{{- if eq .Values.maintenance.secretKind "sealedSecret" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ template "regatta.name" . }}-maintenance-token
  labels:
    {{- include "regatta.labels" . | nindent 4 }}
spec:
  encryptedData:
    token: {{ .Values.maintenance.token }}
{{- end }}
{{- end }}
