{{ if eq "plaintext" .Values.api.tls.mode }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "regatta.name" . }}-api-cert
  labels:
    {{- include "regatta.labels" . | nindent 4 }}
data:
  tls.crt: {{ .Values.api.tls.cert | b64enc }}
  tls.key: {{ .Values.api.tls.key | b64enc }}
{{ end }}
