{{- if .Values.tables.enabled }}
{{- if eq .Values.tables.token.secretKind "plaintext" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "regatta.name" . }}-tables-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "regatta.labels" . | nindent 4 }}
data:
  token: {{ .Values.tables.token.value | b64enc }}
{{- end }}
{{- if eq .Values.tables.token.secretKind "sealedSecret" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ template "regatta.name" . }}-tables-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "regatta.labels" . | nindent 4 }}
spec:
  encryptedData:
    token: {{ .Values.tables.token.value }}
{{- end }}
{{- end }}
