{{ if eq "plaintext" .Values.replication.tls.mode }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "regatta.name" . }}-replication-cert
  labels:
    {{- include "regatta.labels" . | nindent 4 }}
data:
  ca.crt: {{ .Values.replication.tls.ca | b64enc }}
  tls.crt: {{ .Values.replication.tls.cert | b64enc }}
  tls.key: {{ .Values.replication.tls.key | b64enc }}
{{- else if eq "auto" .Values.replication.tls.mode }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "regatta.name" . }}-replication-cert
  labels:
    {{- include "regatta.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  {{- $altNames := list ( printf "%s-replication.%s" (include "regatta.name" .) .Release.Namespace ) ( printf "%s-replication.%s.svc" (include "regatta.name" .) .Release.Namespace ) -}}
  {{- $ca := genCA "regatta-ca" 365 -}}
  {{- $cert := genSignedCert ( printf "%s-replication" ( include "regatta.name" . ) ) nil $altNames 365 $ca }}
  ca.crt: {{ $ca.Cert | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end}}
