apiVersion: v1
kind: Service
metadata:
  name: {{ template "regatta.name" . }}-api
  labels:
    {{- include "regatta.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "regatta.selectorLabels" . | nindent 6 }}
  ports:
  - name: https-api
    targetPort: https
    port: {{ .Values.api.port }}
