apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "regatta.name" . }}
  labels:
    {{- include "regatta.labels" . | nindent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
{{ toYaml . }}
{{- end }}
