apiVersion: v1
kind: Service
metadata:
  name: {{ template "regatta.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "regatta.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "regatta.selectorLabels" . | nindent 6 }}
  ports:
  - name: cluster
    targetPort: cluster
    port: {{ .Values.cluster.port }}
  - name: https
    targetPort: https
    port: {{ .Values.api.port }}
  - name: http-metrics
    targetPort: http-metrics
    port: {{ .Values.metricsPort }}
  publishNotReadyAddresses: true
