apiVersion: v1
kind: Service
metadata:
  name: {{ template "regatta.name" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "regatta.labels" . | nindent 4 }}
  {{ with .Values.api.service.annotations }}
  annotations:
    {{ . | toYaml | nindent 4 }}
  {{ end }}
spec:
  {{- if .Values.api.service.clusterIP }}
  clusterIP: {{ .Values.api.service.clusterIP }}
  {{- end }}
  type: {{ .Values.api.service.type }}
  {{- if .Values.api.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.api.service.externalTrafficPolicy }}
  {{- end }}
  selector:
    {{- include "regatta.selectorLabels" . | nindent 6 }}
  ports:
  - name: https-api
    targetPort: https
    port: {{ .Values.api.port }}
