{{ if and .Values.replication.server.enabled (eq .Values.mode "leader") }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "regatta.name" . }}-replication
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "regatta.labels" . | nindent 4 }}
  {{ with .Values.replication.server.service.annotations }}
  annotations:
    {{ . | toYaml | nindent 4 }}
  {{ end }}
spec:
  type: {{ .Values.replication.server.service.type }}
  externalTrafficPolicy: {{ .Values.replication.server.service.externalTrafficPolicy }}
  selector:
    {{- include "regatta.selectorLabels" . | nindent 6 }}
  ports:
  - name: https-repl
    targetPort: https-repl
    port: {{ .Values.replication.server.port }}
{{ end }}
