{{- if eq .Values.source.token.secretKind "plaintext" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "regatta-backup.name" . }}-maintenance-token
  labels:
    {{- include "regatta-backup.labels" . | nindent 4 }}
data:
  token: {{ .Values.source.token.value | b64enc }}
{{- end }}
{{- if eq .Values.source.token.secretKind "sealedSecret" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ template "regatta-backup.name" . }}-maintenance-token
  labels:
    {{- include "regatta-backup.labels" . | nindent 4 }}
spec:
  encryptedData:
    token: {{ .Values.source.token.value }}
{{- end }}
{{- if eq .Values.source.ca.secretKind "plaintext" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "regatta-backup.name" . }}-api-cert
  labels:
    {{- include "regatta-backup.labels" . | nindent 4 }}
data:
  ca.crt: {{ .Values.source.ca.value | b64enc }}
{{- end }}
{{- if eq .Values.source.token.secretKind "sealedSecret" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ template "regatta-backup.name" . }}-api-cert
  labels:
    {{- include "regatta-backup.labels" . | nindent 4 }}
spec:
  encryptedData:
    ca.crt: {{ .Values.source.token.value }}
{{- end }}
