{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "regatta-backup.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "regatta-backup.labels" . | nindent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
{{ toYaml . }}
{{- end }}
{{- end }}
