{{ if eq "plaintext" .Values.replication.tls.mode }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "regatta.name" . }}-replication-cert
  labels:
    {{- include "regatta.labels" . | nindent 4 }}
data:
  ca.crt: {{ .Values.replication.tls.ca | b64enc }}
  tls.crt: {{ .Values.replication.tls.cert | b64enc }}
  tls.key: {{ .Values.replication.tls.key | b64enc }}
{{ end }}
